version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.IntegrationTests
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - new_gateway_network


networks:
  new_gateway_network:
      external: true
      name: identityproviderapi_new_gateway_network